title: Shop Smart
email: allothar@gmail.com
extension:
  name: Shop Smart
  url: https://chromewebstore.google.com/detail/shopgpt/ibcedmodajmmdeblcdbjehihcnkelfcj
description: >-
  Super Duper Shopping Assistant Powered By GPT
url: "https://phabricator.leyantech.com"
baseurl: "/shop-smart"

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
